# Generated by Django 5.2.7 on 2025-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='priorite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
